name: Update event
on:
  schedule:
    - cron: '10 * * * *'
  workflow_dispatch:
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: node update-event.js
        env:
          WIKI_USER: ${{ secrets.WIKI_USER }}
          WIKI_PASS: ${{ secrets.WIKI_PASS }}
